### ISSUE TITLE
Can you explain the features used in your code?

### ISSUE THREAD

**Issue by gaopeng-eugene** [alexanderrichard/NeuralNetwork-Viterbi#2]

**Comment by gaopeng-eugene** [comment]
self.features[video]: the feature array of the given video (dimension x frames)


any explanation about the feature dimension 64.

**Comment by alexanderrichard** [comment]
The features are Fisher vectors of improved dense trajectories computed over a window of size 20 around each frame. The result has been projected to 64 dimensions using PCA.

**Comment by gaopeng-eugene** [comment]
Thank you so much for your reply.
If I want to carry out research in weakly supervised action detection, fisher vector is the default feature? Any reason why fisher vector is chosen instead of other features?

**Comment by gaopeng-eugene** [comment]
Another question

It seems the feature in the beginning frame is all zero. Any explanation for that?

**Comment by alexanderrichard** [comment]
"Any reason why fisher vector is chosen instead of other features?"
Deep architectures do not work too well if there is no clear label assignment to the frames. Also, datasets like Breakfast are mainly motion driven and do not rely on appearance too much, which is the reason I3D usually does not work much better than dense trajectories. There are other datasets, where I3D features will work much better.
Dense trajectories anyway need to be in the paper because you want to have a fair comparison of your method to other approaches.

"It seems the feature in the beginning frame is all zero. Any explanation for that?"
Yes. Dense Trajectories are computed over a range of 15 frames. Considering the window size of 20, the first time 15 frames are covered by the window [t-10, t+10] is at frame 5. So, all preceding frames are zeros.
Note that zeros also occur if there is no motion at all.

**Comment by gaopeng-eugene** [comment]
Cool. Learned a lot from your paper, code and your amazing reply.
