### ISSUE TITLE
Regarding Viterbi decoding

### ISSUE THREAD

**Issue by wlin-at** [alexanderrichard/NeuralNetwork-Viterbi#6]
Hi Alex,
I have another two issues regarding the Viterbi decoding.
1. For the auxiliary function Q(t,l,c.h), you distinguish two cases
(1) when the frame t stays in the same label, you multiply the function with  the frame score of the last label, which is line 90 in `utils/viterbi.py`
```
score = hyp.score + self.frame_score(frame_scores, t, label)
```
(2) when the frame t goes to the next label, you multiply the function with the frame score of the new label,  the length model score (Poisson probability of the last segment which just ends) and also the grammar score (just to check whether the new label is a valid successor), as in line 98
```
score = hyp.score + self.frame_score(frame_scores, t, label) + self.length_model.score(length, label) + self.grammar.score(context, new_label)
```
Therefore, here the frame score should be `self.frame_score(frame_scores, t, new_label)` instead of `self.frame_score(frame_scores, t, label)`, right? Please forgive me if I have misunderstood the auxiiiary function.

2. In the trackback function, I guess you want to add all the missing frames (remainder of sampling of every 30 frames) to the last segment (which is always SIL label 0), as in line 127-128
```
segments[0].length += n_frames - len(labels) # append length of missing frames
labels += [hyp.traceback.label] * (n_frames - len(labels)) # append labels for missing frames
```
However, you add the number of missing frames to the length of the first segment and then the labels of missing frames to end of `labels`. In this case, the returned `labels` and `segments` do not correspond to each other in the first and last segment. (This has actually no big effect as `segment` was never used during the training.)

Regards

**Comment by alexanderrichard** [comment]
Regarding your first question:
We add the frame score of frame t with label 'label'. The transition in the grammar happens before the first frame of the next segment is read, so only here we need new_label. It might be easier to understand if you look at the code for segment end: We add the frame_score of the last observed label, then Poisson length of the label, and transition with the grammar into the sequence end label (which is a virtual label only indicating end of the sequence, i.e. no frame can have this label).
So, the implementation is correct here.

For the second question:
Good catch. Adding to segment[0] is fine because this is the last segment (traceback goes backwards trough the hypotheses), see that segments is reversed later.
For labels, however, we should add some values of  labels[0] to the beginning. Reason: Also labels is reversed, so this would be equivalent to adding the last label to the end of labels. Will fix it next week. It's not a crucial thing since it only distorts the result by 30 frames in the worst case.

**Comment by wlin-at** [comment]
Thanks for the explanation.
Regarding the first question:
by "the code for segment end", did you mean the function `finalize_decoding`? in line 108 `score = hyp.score + self.length_model.score(length, label) + self.grammar.score(context, self.grammar.end_symbol())`, you only add the Poisson length of the last observed label and grammar score of the end label (no frame score of the last observed label is added).
On the contrary, in the function `init_decoding` line 79 `score = self.grammar.score(context, label) + self.frame_score(frame_scores, self.frame_sampling - 1, label)`, you add the frame score of the `label` which is actually the "new label" here (which is always 0 SIL after start symbol) since the current label is the start symbol and there is no frame score for start symbol.
For example, in init_decoding, key (-1, 0, sampling_rate = 30) has score (frame scores of label 0 at frames 0 - 29 + grammar score)
key (-1, 0, sampling_rate = 30x2 = 60) corresponding to sequence (-1, 0, 0) has score (frame scores of label 0 at frames 0-29 + frame scores of label 0 at frames 30-59 + grammar score )
key (-1, 0, 6 sampling_rate = 30) corresponding to sequence (-1, 0, 6) has score (frame scores of label 0 at frames 0-29 + frame scores of label 0 at frames 30-59 + grammar score ) ---->  in your implementation ----> however, I think the score for key (-1, 0, 6 sampling_rate = 30) should be  (frame scores of label 0 at frames 0-29 + frame scores of label 6 at frames 30-59 + grammar score )
