### ISSUE TITLE
MPII Cooking Dataset

### ISSUE THREAD

**Issue by giulio93** [alexanderrichard/NeuralNetwork-Viterbi#7]
Hi everyone,
I'm trying to use this decoder over [MPII Cooking Dataset](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/human-activity-recognition/mpii-cooking-activities-dataset/)
This dataset is a lot way bigger than Breakfast dataset:
- The longest video il 71K frame long 
- The FPS  ~30
- Number of actions is 64
- Dimension of the features provided is 4000

In order to make training work i modified the parameters in this way:

- frame sampling = 440 in train.py
- buffered_frame_ratio = 10 in train.py
-batch_size = 256 in train.py
- n_old_frames = min( int(7000), self.buffer.n_frames() ) in network.py
- window_size = 50 in network.py

After **2 Days and 4 hours** still, waiting for the training to happen.
So i've decide to abort.

Now i'm planning to:

1. Reduce the number of frame per action.
2. Augmenting the window stride, now window stop over each frame.
3. Reduce features dimensionality, perhaps creating Fisher Vectors.

I was wondering also if this type of Dataset fits the purpose of this Decoder, or since the action are too long, i should find another way... any ideas, suggestion or critic is really appreciated!

**Comment by alexanderrichard** [comment]
Hi Giulio,
I am aware of the problems with the Python code on large datasets. I used a C++ implementation for the paper, which was much faster but also quite complicated, so I decided to publish a more user-friendly python version.

The most costly part for you is probably the Viterbi alignment/decoding. Most promising steps will be:
- buffered_frame_ratio = 5 (still worked well on Breakfast)
- PCA on the features. We did the same to get 64-dim features on Breakfast rather than high-dimensional iDT features.
- Sample the data at 5 or 10 FPS

Also note that currently a window of 21 frames around each frame is used to train the LSTM efficiently. This gets expensive for larger datasets, you might want to switch to other tricks, a smaller window, etc... However, I ran experiments on MPII Cooking with said C++ implementation back then and did not have issues (with 64-dim features). We should still have those lower-dimensional MPII-Cooking features. Please reach out to one of my co-authors.

Hope that helps!
Alex
